# Script generated by WinScript
# Check if the script is running as admin
$ProgressPreference = "SilentlyContinue"
$ErrorActionPreference = "SilentlyContinue"
if (-not ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) { Write-Host "This script requires administrator privileges."`n"Please run WinScript as an administrator." -ForegroundColor Red; pause ; exit }
Write-Host "-- Updating Winget" -ForegroundColor Green
$v = winget -v; if ([version]($v.TrimStart('v')) -lt [version]'1.7.0') { Write-Output '-- - Old Winget version detected, upgrading.'; Set-Location $env:USERPROFILE; Invoke-WebRequest -Uri 'https://aka.ms/getwinget' -OutFile 'winget.msixbundle'; Add-AppPackage -ForceApplicationShutdown .\winget.msixbundle; Remove-Item .\winget.msixbundle } else { Write-Output 'Winget is already up to date, skipping upgrade.' }
Write-Host -- Installing these apps: 
Write-Host -- Google.Chrome RARLab.WinRAR VideoLAN.VLC Zoom.Zoom Adobe.Acrobat.Reader.64-bit Microsoft.Office
Stop-Process -Name explorer -Force -ErrorAction SilentlyContinue | Start-Process explorer.exe | Start-Process cmd.exe -ArgumentList '/k "winget install Google.Chrome RARLab.WinRAR VideoLAN.VLC Zoom.Zoom Adobe.Acrobat.Reader.64-bit Microsoft.Office --accept-source-agreements --accept-package-agreements --force"'
# Pause the script
Pause
# Exit the script
Stop-Process -Name explorer -Force -ErrorAction SilentlyContinue
Start-Process explorer.exe
exit