# Script generated by WinScript
# Check if the script is running as admin
$ProgressPreference = "SilentlyContinue"
$ErrorActionPreference = "SilentlyContinue"
if (-not ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) { Write-Host "This script requires administrator privileges."`n"Please run WinScript as an administrator." -ForegroundColor Red; pause ; exit }
Write-Host "-- Creating a restore point" -ForegroundColor Green
Enable-ComputerRestore -Drive $env:SystemDrive ; Checkpoint-Computer -Description "RestorePoint1" -RestorePointType "MODIFY_SETTINGS"
Write-Host '-- Running Disk Clean-up' -ForegroundColor Green
cleanmgr /verylowdisk /sagerun:5
Write-Host '-- Deleting Temp files' -ForegroundColor Green
Remove-Item -Path "C:\Windows\Temp\*" -Recurse -Force
Remove-Item -Path "C:\Windows\Prefetch\*" -Recurse -Force
Write-Host '-- Emptying Recycle Bin' -ForegroundColor Green
$bin = (New-Object -ComObject Shell.Application).NameSpace(10); $bin.items() | ForEach { Write-Host "Deleting $($_.Name) from Recycle Bin"; Remove-Item $_.Path -Recurse -Force }
Write-Host '-- Resetting Network' -ForegroundColor Green
ipconfig /flushdns
ipconfig /release | Out-Null
ipconfig /renew | Out-Null
# Pause the script
Pause
# Exit the script
Stop-Process -Name explorer -Force -ErrorAction SilentlyContinue
Start-Process explorer.exe
exit



<#
# Requires administrator privileges to run successfully.

# Function to pause the script at the end
function Pause-Script {
    Write-Host "`n"
    Write-Host "----------------------------------------------------" -ForegroundColor Cyan
    Write-Host "Script execution completed." -ForegroundColor Green
    Write-Host "Press Enter to close this window..." -ForegroundColor Yellow
    $null = Read-Host
}

# --- 1. Create a System Restore Point ---
Write-Host "Attempting to create a System Restore Point..." -ForegroundColor Blue

try {
    # Check if System Restore is enabled on C: drive (optional but recommended check)
    $sysRestoreStatus = Get-ComputerRestorePoint -LastStatus | Select-Object -ExpandProperty Status
    if ($sysRestoreStatus -eq "Off") {
        Write-Warning "System Restore is disabled on the C: drive. Cannot create a restore point."
    }
    else {
        # The Checkpoint-Computer cmdlet is the recommended method for Windows 11
        # A description with a dynamic timestamp is used for easy identification
        $description = "Automated Maintenance - $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
        Checkpoint-Computer -Description $description -RestorePointType "MODIFY_SETTINGS" -ErrorAction Stop
        Write-Host "Successfully created System Restore Point: '$description'" -ForegroundColor Green
    }
}
catch {
    Write-Error "Failed to create a System Restore Point. Error: $_"
}

Write-Host "`n"

# --- 2. Run Disk Clean-up ---
Write-Host "Starting Disk Clean-up..." -ForegroundColor Blue

try {
    # Use cleanmgr.exe with /sagerun:1 to run a pre-configured set of cleanup options
    # The /sagerun:1 command executes the cleanup with the settings saved previously via /sageset:1
    # Note: You may need to run 'cleanmgr.exe /sageset:1' manually once to select desired items
    $cleanmgrPath = "$env:SystemRoot\System32\cleanmgr.exe"
    Start-Process $cleanmgrPath -ArgumentList "/sagerun:1" -Wait
    Write-Host "Disk Clean-up process initiated and completed." -ForegroundColor Green
}
catch {
    Write-Error "Failed to run Disk Clean-up. Ensure cleanmgr.exe is available and check permissions. Error: $_"
}

# --- 3. Pause the script at the end ---
Pause-Script

#>


